name: SelfGroup
main: net.yeticraft.xxtraineexx.SelfGroup.SelfGroup
version: 3.0
description: >
             YetiFaction
commands:
  yetifaction:
    description: Primary command used to access YetiFaction
    usage: "Usage: '/yetifaction help'"
  yf:
    description: Primary command used to access YetiFaction
    usage: "Usage: '/yf help'"